[workspace]

members = [
    "bin/client",
    "bin/server",
    "lib/counter",
    "lib/network",
    "lib/service",
]

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
incremental = false
