[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.2.8"
env_logger = "0.9.0"
network = { version = "0.1.0", path = "../../lib/network" }
tokio = { version = "1.19.2", features = ["full"] }
